namespace MonopoSaver.DataModels {
    class Board {
        public static readonly List<string> Pieces = new List<string>() {
            "Cello",
            "Ecto Goggles",
            "Glasses",
            "PKE Meter",
            "Proton Pack",
            "Radio"
        };
        
        public static readonly List<Prop> Places = new List<Prop>() {
            new Prop(){Name="Go", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Reading Room", Color="#825a2c", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Roaming Vapor 1", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Basement", Color="#825a2c", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Library Ghost", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Ecto-1 1", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Paranormal Studies Lab", Color="#1ba1e2", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Roaming Vapor 2", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Dana's Living Room", Color="#1ba1e2", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Dana's Kitchen", Color="#1ba1e2", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="In Jail", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Just Visiting Jail", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Hotel Lobby", Color="#f472d0", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Slimer", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Twelfth Floor", Color="#f472d0", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Ballroom", Color="#f472d0", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Ecto-1 2", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Sleeping Quarters", Color="#fa6800", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Roaming Vapor 3", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Janine's Desk", Color="#fa6800", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Symphony Hall", Color="#fa6800", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Free Parking", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Louis's Living Room", Color="#e51400", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Roaming Vapor 4", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Louis's Bedroom", Color="#e51400", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Tavern Restaurant", Color="#e51400", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Ecto-1 3", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Subway Entrance", Color="#e3c800", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Headquarters", Color="#e3c800", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Vince Clortho", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Storage Facility", Color="#e3c800", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Go To Jail", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="City Hall", Color="#008a00", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Mayor's Office", Color="#008a00", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Roaming Vapor 5", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="550 Central Park West", Color="#008a00", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Ecto-1 4", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Roaming Vapor 6", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Spook Central", Color="#0050ef", isMortgaged=0, Ownable=true, Houses=0},
            new Prop(){Name="Stay Puft", Color="#000000", isMortgaged=0, Ownable=false, Houses=0},
            new Prop(){Name="Temple of Gozer", Color="#0050ef", isMortgaged=0, Ownable=true, Houses=0},
        };
    }
}